appName: emailservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/emailservice
appVersion: v0.9.0
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"

servicePort: 8080
serviceType: ClusterIP