appName: paymentservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/paymentservice
appVersion: v0.9.0
containerPort: 50051
containerEnvVars:
- name: PORT
  value: "50051"
- name: DISABLE_PROFILER
  value: "1" 

servicePort: 50051
serviceType: ClusterIP