appName: productcatalogservice
appReplicas: 2
appImage: gcr.io/google-samples/microservices-demo/productcatalogservice
appVersion: v0.9.0
containerPort: 3550
containerEnvVars:
- name: PORT
  value: "3550"

servicePort: 3550
serviceType: ClusterIP